### ISSUE TITLE
"Getting Workouts"

### ISSUE THREAD

**Issue by colinbourhill** [DariuS231/D43.GarminConnect.Scheduler#11]
Hi there, I have installed the Garmin Connect Scheduler extension you have created for Chrome.  When I attempt to use the extension it appears to get hung up on 'Getting Workouts'.  I never get to the point where I can see the workouts to schedule.

**Comment by DariuS231** [comment]
Hi @colinbourhill I am aware of that and I am working on the fix, Garmin changed API and I need to adapt the extension to the new changes.

Will let you know when I release a new version.

**Comment by colinbourhill** [comment]
No worries, I wasn't sure if it was something to do with my account (had
Garmin Connect for ages so there is a stupidly large amount of workout data
it is trying to look up).  Appreciate you getting back to me though.

Thanks,
Colin

**Comment by DariuS231** [comment]
@colinbourhill All fixed now,  I just sent the package to google and is under review. It should be available within the day.

Regards,
Dario
