### ISSUE TITLE
Schedule -1 Offset

### ISSUE THREAD

**Issue by pdeschen** [DariuS231/D43.GarminConnect.Scheduler#13]
Looks like to get a workout scheduled weekly on monday and wednesday, I had to pick tuesday and Thursday There seems to be an offset issue somewhere.

I quickly tried to find a solution but could not pin point the code involved. 

Thanks for that extension!

**Comment by pdeschen** [comment]
Here is a screenshot. I had to select Saturday/Monday/Thursday to get a schedule on Friday/Sunday/Wednesday.

<img width="602" alt="image" src="https://github.com/DariuS231/D43.GarminConnect.Scheduler/assets/153048/2220a67d-319b-4ba6-bdd3-c6f674709e90">

**Comment by DariuS231** [comment]
@pdeschen this looks like a localisation issue and date formatting. I will try to replicate an environment similar to yours and fix this issue. 

Can you please tell me your locale settings?

**Comment by pdeschen** [comment]
`navigator.language` is `en-US`

Let me know if you need more info

**Comment by DariuS231** [comment]
@pdeschen I was unable ti replicate the issue but I believe the change I just made will fix the problems for you. Will let you know when is all published and ready to be tested
