### ISSUE TITLE
Delete scheduled workouts

### ISSUE THREAD

**Issue by bgaborg** [DariuS231/D43.GarminConnect.Scheduler#8]
First, thanks for working on this plugin!

I scheduled a workout many times a week over many months. I see no functionality to remove this schedule automatically. Should I remove every single occurrence by hand manually? 

I thought there is already a feature for this. If there is, please share how to do it. If there is no such feature, this is a feature request.

**Comment by DariuS231** [comment]
Good to hear you are finding it useful.

This feature you are talking about does not exist at the moment but I see the value of it and have even needed it a few times myself. 

I just added it ad a new enhancement and will try to find some time to work on it. 

Thanks for the feedback and will keep you updated.

**Comment by nkarlusic** [comment]
Hello, 

Also wanted to thank you for this extension, but would like to ask is there any progress on this feature to remove scheduled workouts?

Cheers! :)

**Comment by nkarlusic** [comment]
I don't want to delete the workout in general, I would only like to delete if from the calendar if possible?

I would like to replace current workouts I have for a given day, with a different workout, could you maybe add something like that, a replace option? 

Thank you for your quick response! 🥇

**Comment by nkarlusic** [comment]
That would be great, thank you, anything will help! :)

**Comment by DariuS231** [comment]
@bgaborg and @nkarlusic  the new version with this change is out now. Go ahead give it a try and let me know what you think.
